sudo: required
services:
  - docker

env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1

#before_install:
#  - openssl ....-d # command copied from the encryption of the secret json file
#  - curl https://sdk.cloud.google.com | bash > /dev/null;
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components update kubectl
#  - gcloud auth activate-service-account --key-file service-account.json
#  - gcloud config set project <GOOGLE-projectnameID>
#  - gcloud config set compute/zone <location of project>
#  - gcloud config container clusters get-credentials <name of cluster>
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master
